# Generated by Django 3.1 on 2021-03-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_web', '0006_auto_20210302_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='soc_fb',
            field=models.CharField(blank=True, default='@', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='soc_ig',
            field=models.CharField(blank=True, default='@', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='soc_tw',
            field=models.CharField(blank=True, default='@', max_length=60, null=True),
        ),
    ]
