# Generated by Django 3.1 on 2021-03-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News_web', '0007_auto_20210303_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedias',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_email', serialize=False, to='News_web.author')),
                ('soc_fb', models.CharField(blank=True, default='@', max_length=60, null=True)),
                ('soc_tw', models.CharField(blank=True, default='@', max_length=60, null=True)),
                ('soc_ig', models.CharField(blank=True, default='@', max_length=60, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='soc_fb',
        ),
        migrations.RemoveField(
            model_name='author',
            name='soc_ig',
        ),
        migrations.RemoveField(
            model_name='author',
            name='soc_tw',
        ),
    ]
