# Generated by Django 3.1 on 2021-03-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_web', '0008_auto_20210303_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedias',
        ),
    ]
