# Generated by Django 3.1 on 2021-03-03 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News_web', '0009_delete_socialmedias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soc_fb', models.CharField(blank=True, default='@', max_length=60, null=True)),
                ('soc_tw', models.CharField(blank=True, default='@', max_length=60, null=True)),
                ('soc_ig', models.CharField(blank=True, default='@', max_length=60, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
