# Generated by Django 3.1 on 2021-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_web', '0011_auto_20210303_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_color',
            field=models.CharField(default='#c63e40', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialmedias',
            name='soc_fb',
            field=models.CharField(default='@', max_length=60, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='socialmedias',
            name='soc_ig',
            field=models.CharField(default='@', max_length=60, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='socialmedias',
            name='soc_tw',
            field=models.CharField(default='@', max_length=60, null=True, verbose_name='Twitter'),
        ),
    ]
